# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba273077976b4878f620a695ee1a3019e5673cd8e45363a6d142e1d4199d4b01f42631bda5e233414edef6c6cbfb3d72555df1067bd284eb779a0b078e87df4a

test:
  secret_key_base: 32e8bc827f978d470c6ee4656000ca4aa294dbee55de789766356cfc4d5a5698701b7f01bea381f9612ec386dff635abfc599da7f04453587435ef42620e2802

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
